export const PATH = {
    home: '/',
    login: '/login',
    signUp: '/sign-up',
    user: '/user',
    printZero: '/user/print/page-1',
    printOne: '/user/print/page-2',
    printTwo: '/user/print/page-3',
    printThree: '/user/print/page-4',
    about: '/about',
    historyPrint: '/user/history/print',
    historyBuy: '/user/history/buy',
    loginRoute: '/loginRoute',
    admin: '/admin',
    adminConfig: '/admin/config',
    adminPrinter: '/admin/printer',
    adminViewFeedback: '/admin/viewFeedback',
    adminViewHistory: '/admin/viewHistory',
}